services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    UserBundle\DataFixtures:
        #resource: '../../src/UserBundle/DataFixtures/'
        tags: ['doctrine.fixture.orm']